name: "RSpec Report"
description: "A GitHub Action that report RSpec failure."
branding:
  icon: alert-triangle
  color: red
author: "aki77"
inputs:
  token:
    description: "Github token"
    required: false
    default: "${{ github.token }}"
  json-path:
    description: "JSON File path"
    required: true
  title:
    description: "Title"
    default: "# :cold_sweat: RSpec failure"
    required: false
  hideFooterLink:
    description: "Hide footer link"
    default: "false"
    required: false
  comment:
    description: "Set this if want to comment report to pull request"
    default: "true"
    required: false
  pull-request-id:
    description: "ID of the pull request to comment the report on"
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
