name: "RSpec Report"
description: "A GitHub Action that report RSpec failure."
branding:
  icon: alert-triangle
  color: red
author: "aki77"
inputs:
  token:
    description: "Github token"
    required: true
  json-path:
    description: "JSON File path"
    required: true
  title:
    description: "Title"
    default: "# :cold_sweat: RSpec failure"
    required: false
  hideFooterLink:
    description: "Hide footer link"
    default: "false"
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
